source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'XXStackView_Example' do
  pod 'XXStackView', :path => '../'
  

# ------------------  变动较小的组件或者是其他三方库引入版本号 -----------------

target 'XXStackView_Tests' do
    inherit! :search_paths

    
  end
end
